In [22]:
import tensorflow as tf

## Variables

In [23]:
x = 1
y = x + 9
print (y)

10


In [24]:
x = tf.Variable(3)
y = tf.Variable(4)
#z=3
f = x*x*y + y + 2

In [25]:
sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)
print(result)

42


## Defining multidemensional array

In [26]:
scaler = tf.constant([2])
vector = tf.constant([3,4,5])
matrix = tf.constant([[1,2,3],[3,4,6],[9,5,2]])
tensor = tf.constant([[[1,2,3],[3,4,6],[9,5,2]],[[1,4,6],[6,4,0],[3,5,2]],[[0,2,5],[3,3,6],[2,5,1]]])

In [27]:
with tf.Session() as session:
    result=session.run(scaler)
    print('Scaler:\n',result)
    
    result=session.run(vector)
    print('Vector:\n',result)

Scaler:
 [2]
Vector:
 [3 4 5]


In [29]:
with tf.Session() as session:    
    result=session.run(matrix)
    print('Matrix:\n',result)

Matrix:
 [[1 2 3]
 [3 4 6]
 [9 5 2]]


In [33]:
with tf.Session() as session:    
    tensor=session.run(tensor)
    print('Tensor:\n',tensor)

Tensor:
 [[[1 2 3]
  [3 4 6]
  [9 5 2]]

 [[1 4 6]
  [6 4 0]
  [3 5 2]]

 [[0 2 5]
  [3 3 6]
  [2 5 1]]]


In [37]:
print(tensor[2][2])

[2 5 1]


## Numpy 

In [21]:
import numpy as np
tensor_2d = np.array([(1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12)])
print (tensor_2d[0][:3])

[1 2 3]


#  Placeholder

In [9]:
a=tf.placeholder(tf.float32)

In [10]:
b=a*2

In [11]:
with tf.Session() as session:
    result=session.run(b, feed_dict={a:3.5})
    print(result)

7.0


### Placeholder pass the data with feed_dict argument

In [12]:
dictionary = {a: [[1,2,3],[3,4,6],[9,5,2]]}

In [13]:
with tf.Session() as session:
    result=session.run(b, feed_dict=dictionary)
    print(result)

[[ 2.  4.  6.]
 [ 6.  8. 12.]
 [18. 10.  4.]]
